services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rahunu
      POSTGRES_USER: rahunu
      POSTGRES_PASSWORD: rahunu
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rahunu -d rahunu"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://rahunu:rahunu@db:5432/rahunu?schema=public
      AUTH_SECRET: ${AUTH_SECRET:?AUTH_SECRET environment variable is required}
      AUTH_URL: http://localhost:3000
      NODE_ENV: production
      UPLOAD_DIR: /app/storage/uploads
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/storage/uploads
volumes:
  db: {}
  uploads: {}
